spring:
  datasource:
    url: jdbc:mysql://localhost:3307/identity_db?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
    username: Admin
    password: Admin@$20260702
    driver-class-name: com.mysql.cj.jdbc.Driver
  mail:
    host: smtp.gmail.com
    port: 587
    username: e20318@eng.pdn.ac.lk
    password: emaucnmosipxqump
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
          connectiontimeout: 5000
          timeout: 5000
          writetimeout: 5000
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
    open-in-view: false

  flyway:
    enabled: true
    baseline-on-migrate: true
    baseline-version: 0
    baseline-description: init
    url: ${spring.datasource.url}
    user: ${spring.datasource.username}
    password: ${spring.datasource.password}

  data:
    redis:
      host: localhost
      port: 6379
      password: ${REDIS_PASSWORD:redis123}
      timeout: 2s

management:
  zipkin:
    tracing:
      endpoint: http://localhost:9411/api/v2/spans

bootstrap:
  super-admin:
    email: superadmin@genzipher.com
    password: SuperAdmin@20260702


security:
  jwt:
    secret: ${JWT_SECRET:Ro7m3HxWZlse6kmdCNsGJXZr570I0in3NEF5Fr8UzziDJqqMn1yL7eYpXlB}
    issuer: genzipher-identity
    access-ttl-seconds: 900
    refresh-ttl-seconds: 604800
    max-idle-seconds: 1800

app:
  mail:
    from: ${MAIL_FROM:${spring.mail.username}}
  password-reset:
    code-ttl-seconds: 300   # 5 minutes

logging:
  level:
    org.springframework.security: DEBUG

server:
  port: 8050
